# Generated by Django 4.2.20 on 2025-06-25 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveIntegerField()),
                ('puntos', models.PositiveIntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progreso', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=100)),
                ('foto', models.ImageField(default='imagenes/fotoDefault.png', upload_to='imagenes/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=900)),
                ('destacado', models.BooleanField(default=False)),
                ('desbloqueado', models.BooleanField(default=False)),
                ('progreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='sistemaWeb.progresojuego')),
            ],
        ),
        migrations.CreateModel(
            name='AprendizajeJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('imagen', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=200)),
                ('fuente', models.CharField(max_length=200)),
                ('destacado', models.BooleanField(default=False)),
                ('desbloqueado', models.BooleanField(default=False)),
                ('progreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendizajes', to='sistemaWeb.progresojuego')),
            ],
        ),
        migrations.CreateModel(
            name='AporteAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('oxigenoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbonoTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('co2Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaRegistro', models.DateField(auto_now_add=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='sistemaWeb.planta')),
            ],
        ),
    ]
