# Generated by Django 4.2.20 on 2025-06-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='imagen',
            field=models.CharField(default='ruta', max_length=150),
            preserve_default=False,
        ),
    ]
