# Generated by Django 4.2.20 on 2025-06-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresojuego',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='progresojuego',
            name='puntos',
        ),
        migrations.AddField(
            model_name='progresojuego',
            name='cantidadApzjDesbloqueados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progresojuego',
            name='cantidadMsjDesbloqueados',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
