# Generated by Django 4.2.20 on 2025-04-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='carbonoTotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='planta',
            name='fechaRegistro',
            field=models.DateField(auto_now_add=True, default='2024-10-10'),
            preserve_default=False,
        ),
    ]
