# Generated by Django 4.2.20 on 2025-07-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaWeb', '0002_remove_progresojuego_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresojuego',
            name='fechaJuego',
            field=models.DateField(blank=True, null=True),
        ),
    ]
