# Generated by Django 4.2.20 on 2025-07-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaWeb', '0003_progresojuego_fechajuego'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aprendizajejuego',
            unique_together={('progreso', 'titulo')},
        ),
        migrations.AlterUniqueTogether(
            name='mensajejuego',
            unique_together={('progreso', 'titulo')},
        ),
    ]
