# Generated by Django 4.2.20 on 2025-06-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaWeb', '0003_alter_planta_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planta',
            old_name='imagen',
            new_name='foto',
        ),
    ]
