# Generated by Django 4.2.20 on 2025-07-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaWeb', '0004_alter_aprendizajejuego_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aprendizajejuego',
            name='destacado',
        ),
        migrations.RemoveField(
            model_name='mensajejuego',
            name='destacado',
        ),
    ]
