# Generated by Django 4.2.20 on 2025-06-21 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaWeb', '0004_rename_imagen_planta_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default=' ', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MensajeJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=900)),
                ('destacado', models.BooleanField(default=False)),
                ('desbloqueado', models.BooleanField(default=False)),
                ('progreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='sistemaWeb.progresojuego')),
            ],
        ),
        migrations.CreateModel(
            name='AprendizajeJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('imagen', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=200)),
                ('fuente', models.CharField(max_length=200)),
                ('destacado', models.BooleanField(default=False)),
                ('desbloqueado', models.BooleanField(default=False)),
                ('progreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendizajes', to='sistemaWeb.progresojuego')),
            ],
        ),
    ]
