# Generated by Django 4.2.20 on 2025-08-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaWeb', '0005_remove_aprendizajejuego_destacado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendizajejuego',
            name='fuente',
            field=models.TextField(),
        ),
    ]
