# Generated by Django 4.2.20 on 2025-08-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaWeb', '0006_alter_aprendizajejuego_fuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='etapa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
